# Generated by Django 4.2.2 on 2023-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=25)),
                ('dest', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
